#!/usr/bin/env python3
"""Contenu des guides Klynera.

Chaque guide est écrit à la main : ce sont des pages de réponse, pas des pages générées.
Le chapô répond directement à la question posée — c'est ce que les moteurs IA citent.
"""

# slug, titre SEO, H1, description, chapô, [(h2, [paragraphes])], [(question, réponse)], service lié
GUIDES = [

("frequence-nettoyage-vitrine-commerce",
 "À quelle fréquence faire nettoyer la vitrine d’un commerce",
 "À quelle fréquence faire nettoyer <em>une vitrine de commerce</em>",
 "Toutes les semaines en centre-ville, tous les quinze jours ailleurs : la fréquence de nettoyage d’une vitrine dépend du passage, de l’exposition et du type de commerce.",
 "Pour un commerce de centre-ville, comptez un passage hebdomadaire. En périphérie ou en zone pavillonnaire, un passage tous les quinze jours suffit. Un commerce alimentaire, un salon de coiffure ou un opticien ont besoin d’un rythme plus soutenu qu’une agence ou un cabinet, parce que la vitrine y est touchée et que les projections sont plus fréquentes.",
 [("Ce qui salit une vitrine, et à quelle vitesse",
   ["Une vitrine se salit par trois mécanismes distincts, qui n’ont pas la même vitesse. Les traces de doigts et de museaux apparaissent en quelques heures dès qu’il y a du passage à hauteur d’enfant ou de chien. La poussière et les projections de la rue s’accumulent en quelques jours, plus vite le long d’un axe circulant. Le calcaire et les résidus de pollution, eux, mettent des semaines — mais ce sont les seuls qui s’incrustent réellement dans le verre.",
    "Cette distinction compte, parce qu’elle explique pourquoi espacer les passages coûte plus cher au final. Les deux premiers types partent avec un simple lavage. Le troisième, une fois installé, demande un traitement plus long et parfois un décapage. Une vitrine nettoyée toutes les semaines se fait en quelques minutes ; la même laissée trois mois demande le double de temps."]),
  ("Le rythme selon le type de commerce",
   ["Les commerces à fort contact direct avec la vitre — boulangeries, boucheries, pâtisseries, magasins de jouets, animaleries — justifient un passage hebdomadaire, voire deux en période de forte fréquentation. La vitrine est touchée toute la journée, et les traces se voient immédiatement sur un verre bien éclairé.",
    "Les commerces de service — agences immobilières, assurances, cabinets, opticiens, salons — tiennent généralement sur un rythme hebdomadaire ou bimensuel. Le passage est moins physique, mais la vitrine sert de vitrine au sens propre : elle est regardée avant d’entrer.",
    "Les locaux en zone d’activité, les showrooms et les concessions peuvent descendre à un passage mensuel, à condition que les surfaces soient grandes et peu touchées. En revanche, une façade vitrée exposée plein sud ou en bord de route salit plus vite qu’on ne l’imagine : l’exposition compte autant que le passage."]),
  ("Pourquoi le contrat régulier coûte moins cher par passage",
   ["Un vitrage entretenu se nettoie plus vite. C’est la seule raison, et elle est mécanique : il n’y a pas de couche accumulée à décoller, pas de calcaire à traiter, pas de reprise sur les encadrements. Le temps passé baisse, donc le tarif par passage baisse.",
    "S’ajoute un effet d’organisation : un passage récurrent se cale sur une tournée existante, sans déplacement dédié. C’est ce qui permet de proposer un prix par passage inférieur à celui d’une intervention isolée, sans rogner sur la qualité.",
    "Le calcul à faire n’est donc pas « combien coûte un passage » mais « combien coûte une année ». Douze passages mensuels reviennent souvent moins cher que quatre grosses remises en état, pour un résultat visible en permanence plutôt que quatre fois par an."]),
  ("Le bon moment dans la semaine",
   ["Pour un commerce, le passage idéal se fait avant l’ouverture ou après la fermeture, jamais pendant les heures de pointe. Cela évite de gêner les clients et permet de travailler proprement, sans avoir à déplacer du matériel toutes les deux minutes.",
    "Le jour compte aussi. Une vitrine nettoyée le jeudi ou le vendredi est au mieux de son état pour le week-end, quand la fréquentation est la plus forte. Nettoyée le lundi, elle a déjà repris quatre jours de traces au moment où ça compte le plus."])],
 [("Faut-il nettoyer les vitres l’hiver ?",
   "Oui, et souvent plus qu’en été. La pluie mêlée aux particules de la route laisse des traces qui s’incrustent, et les journées courtes font que la lumière rasante révèle le moindre voile. L’hiver est la saison où une vitrine sale se voit le plus."),
  ("Le nettoyage intérieur est-il nécessaire à chaque passage ?",
   "Rarement. L’intérieur se salit trois à quatre fois moins vite que l’extérieur. Un rythme d’un passage intérieur pour deux ou trois passages extérieurs suffit dans la plupart des commerces, sauf en cas de cuisson ou de manipulation de produits gras."),
  ("Peut-on changer de fréquence en cours de contrat ?",
   "Oui. La bonne fréquence se trouve souvent après deux ou trois mois d’observation. Nous ajustons à la hausse ou à la baisse selon ce que montre le terrain, et le tarif suit.")],
 ("/nettoyage-vitres/", "Nettoyage de vitres")),

("nettoyage-vitres-sans-trace",
 "Nettoyage de vitres sans trace : la méthode professionnelle",
 "Nettoyage de vitres <em>sans trace</em> : la méthode",
 "Mouilleur, raclette en passes croisées, finition microfibre et contrôle au contre-jour : la méthode qui laisse un verre sans voile ni coulure, et pourquoi le chiffon seul n’y arrive jamais.",
 "Une vitre sans trace s’obtient avec trois outils et un ordre précis : un mouilleur pour décoller la saleté, une raclette pour évacuer l’eau en passes croisées, une microfibre pour les bords. Le chiffon seul ne fonctionne pas parce qu’il déplace la saleté au lieu de l’évacuer, et parce qu’il laisse toujours un film d’eau qui sèche en voile.",
 [("Pourquoi le chiffon laisse des traces",
   ["Un chiffon absorbe. C’est exactement le problème : il se charge de la saleté qu’il enlève, puis la redépose plus loin sur la vitre. Au deuxième passage, on étale ce qu’on vient de retirer. C’est ce qui produit ces zones troubles qu’on ne voit qu’en lumière rasante.",
    "S’ajoute la question du séchage. Un chiffon laisse toujours un film d’eau résiduel, trop fin pour qu’on le remarque sur le moment. En séchant, ce film dépose les minéraux qu’il contenait — c’est le voile blanchâtre typique, et il s’incruste un peu plus à chaque fois."]),
  ("Les trois outils, et ce que chacun fait",
   ["Le mouilleur est un manchon en microfibre monté sur un T. Il ne sert pas à essuyer mais à **mouiller abondamment** et à décoller mécaniquement ce qui adhère au verre. Il doit être franchement chargé en eau : un mouilleur trop sec raye et n’enlève rien.",
    "La raclette évacue. Sa lame en caoutchouc doit être nette et sans entaille — une lame ébréchée laisse un trait à chaque passage, et beaucoup de gens attribuent ce trait au produit alors qu’il vient de l’outil. Une lame se change régulièrement, c’est un consommable.",
    "La microfibre ne sert qu’à la finition : les bords, les angles, l’encadrement, l’appui. C’est le seul endroit où elle a sa place. Utilisée sur la surface, elle réintroduit le problème du chiffon."]),
  ("Le geste : les passes croisées",
   ["La raclette se passe en bandes qui se chevauchent d’environ deux centimètres, en essuyant la lame entre chaque passe. Le chevauchement évite les lignes de raccord ; l’essuyage évite de redéposer l’eau chargée.",
    "Sur les grandes surfaces, on alterne le sens entre l’intérieur et l’extérieur — horizontal d’un côté, vertical de l’autre. Cela paraît anecdotique, mais c’est ce qui permet de savoir de quel côté se trouve une trace résiduelle sans avoir à sortir pour vérifier.",
    "Les bords se traitent en dernier, quand toute la surface est déjà évacuée. L’eau qui redescend des encadrements est celle qui crée les coulures : si on essuie les bords en premier, on refait le travail."]),
  ("Le produit, et pourquoi moins vaut mieux",
   ["Un excès de produit est la cause la plus fréquente de voile. Le dosage professionnel est très inférieur à ce que l’intuition suggère : quelques gouttes dans un seau, pas un fond de flacon. Le produit sert à casser la tension superficielle de l’eau, pas à dissoudre la saleté.",
    "L’eau elle-même compte. Dans une région calcaire, une eau du robinet non traitée dépose du calcaire en séchant, quel que soit le geste. C’est ce qui explique qu’un même protocole donne un résultat impeccable ici et médiocre ailleurs."]),
  ("Le contrôle au contre-jour",
   ["Une vitre se vérifie toujours en se plaçant de manière à ce que la lumière la traverse en biais. De face, un voile est invisible ; en lumière rasante, il saute aux yeux. C’est la seule vérification qui vaille, et elle prend dix secondes.",
    "C’est aussi pour cette raison qu’un nettoyage fait par temps de plein soleil est plus difficile : l’eau sèche avant d’être évacuée et laisse des marques. Les professionnels travaillent de préférence à l’ombre ou en début de journée."])],
 [("Le vinaigre blanc marche-t-il vraiment ?",
   "Il dissout le calcaire, donc il aide sur une vitre entartrée. Mais il attaque les joints et les mastics à la longue, et il ne remplace pas la raclette : sans évacuation de l’eau, on obtient une vitre propre et voilée."),
  ("Le papier journal, ça fonctionne ?",
   "C’est un remède ancien qui tenait à la composition des encres d’autrefois. Les encres actuelles ne se comportent plus pareil, et le papier laisse des fibres. Une microfibre fait mieux, pour moins cher."),
  ("Peut-on nettoyer des vitres en hauteur sans nacelle ?",
   "Souvent oui, avec une perche télescopique. Cela couvre la majorité des maisons et beaucoup de vitrines de rez-de-chaussée. Au-delà, ou si l’accès est encombré, il faut un moyen d’élévation — et cela change le devis.")],
 ("/nettoyage-vitres/", "Nettoyage de vitres")),

("que-comprend-nettoyage-fin-de-chantier",
 "Que comprend exactement un nettoyage de fin de chantier",
 "Que comprend <em>un nettoyage de fin de chantier</em>",
 "Dépoussiérage complet, retrait des traces de peinture, d’enduit et de colle, nettoyage des vitres et des menuiseries, dégraissage des sanitaires et finitions : ce qui est inclus, et ce qui ne l’est pas.",
 "Un nettoyage de fin de chantier comprend le dépoussiérage complet des sols, murs, plafonds, plinthes et gaines, le retrait des traces de peinture, d’enduit, de colle et de ciment, le nettoyage des vitres et des menuiseries, le dégraissage et la désinfection des sanitaires et des cuisines, et les finitions — poignées, interrupteurs, luminaires, étiquettes. Il ne comprend ni l’évacuation des gravats ni la dépose de matériel : ce sont des postes distincts.",
 [("Ce qui est toujours inclus",
   ["Le dépoussiérage est le poste le plus lourd, et le plus sous-estimé. La poussière de chantier est fine et se loge partout : au-dessus des portes, dans les rainures de plinthes, dans les grilles de ventilation, derrière les radiateurs. Elle ne s’aspire pas en une passe, et elle se redépose pendant vingt-quatre à quarante-huit heures après le passage des derniers corps d’état.",
    "Le retrait des traces vient ensuite : projections de peinture sur les sols et les vitres, coulures d’enduit, résidus de colle sur les carrelages, laitance de ciment. Chacune demande un traitement différent — une trace de silicone ne s’enlève pas comme une goutte de peinture acrylique, et un voile de ciment sur un carrelage demande un produit acide qu’on ne passe pas sur n’importe quel support.",
    "Viennent enfin les vitres et menuiseries, les sanitaires et cuisines, puis les finitions. Les finitions sont ce qui fait la différence entre « nettoyé » et « livrable » : ce sont elles qu’un acquéreur regarde."]),
  ("Ce qui n’est pas inclus, et pourquoi",
   ["L’évacuation des gravats et des déchets de chantier relève de l’entreprise qui les a produits. Un nettoyeur peut s’en charger, mais c’est une prestation distincte, avec un coût de benne et de transport qui n’a rien à voir avec du nettoyage.",
    "La dépose de protections lourdes, de bâches agrafées ou de plaques de sol collées relève également du chantier. De même pour les réparations : une rayure sur un parquet ou un éclat sur un carrelage ne se nettoient pas, ils se réparent.",
    "Enfin, un nettoyage de fin de chantier n’est pas une remise en état après sinistre. Suie, fumée ou dégât des eaux demandent des produits et des protocoles différents."]),
  ("Une ou deux passes ?",
   ["Sur un chantier de petite taille livré proprement, une passe suffit. Sur un chantier important, ou quand les corps d’état se succèdent jusqu’au dernier moment, deux passes valent mieux : une passe lourde dès la fin des travaux, puis une passe de finition juste avant la livraison.",
    "La raison est mécanique : la poussière fine en suspension met vingt-quatre à quarante-huit heures à retomber. Un chantier nettoyé impeccablement le lundi aura un voile visible le mercredi. La deuxième passe est courte, et c’est elle qui fait la différence à la remise des clés."]),
  ("Qui commande, et qui paie",
   ["Sur une construction neuve, c’est généralement le promoteur ou le maître d’ouvrage qui commande le nettoyage de livraison, parfois l’entreprise générale. Sur une rénovation, c’est le plus souvent l’artisan principal ou le particulier directement.",
    "Le point qui crée le plus de litiges : le « nettoyage de fin de chantier » mentionné dans un marché de travaux désigne parfois un simple balayage, pas une remise en état. Il vaut mieux vérifier ce que recouvre exactement la ligne du devis avant de supposer que c’est inclus."])],
 [("Combien de temps avant la livraison faut-il intervenir ?",
   "Idéalement deux à trois jours avant, avec une passe de finition la veille si le chantier est important. Trop tôt, la poussière résiduelle redescend ; trop tard, il n’y a plus de marge si quelque chose doit être repris."),
  ("Faut-il que le chantier soit totalement terminé ?",
   "Oui pour la passe principale. Un seul corps d’état qui repasse après remet de la poussière partout et annule le travail. Si un artisan doit revenir, mieux vaut décaler ou prévoir une passe de finition."),
  ("Le nettoyage des vitres est-il compris ?",
   "Oui, y compris le retrait des étiquettes et des résidus de pose. C’est justement sur du vitrage neuf que les traces de chantier sont les plus tenaces : adhésifs, silicone, voile de plâtre.")],
 ("/nettoyage-fin-de-chantier/", "Nettoyage de fin de chantier")),

("voile-de-ciment-carrelage-neuf",
 "Voile de ciment sur un carrelage neuf : comment le retirer",
 "Voile de ciment sur un carrelage neuf, <em>comment on le retire</em>",
 "Le voile de ciment est un dépôt laissé par le jointoiement. Il se retire avec un produit acide dilué, en respectant un temps de pose et un rinçage abondant — et surtout pas avec un nettoyant ménager.",
 "Le voile de ciment est le film blanchâtre laissé sur un carrelage par l’eau de jointoiement en séchant. Il se retire avec un décapant acide dilué, appliqué après un temps de séchage complet des joints — au minimum une semaine — laissé en pose quelques minutes, frotté, puis rincé abondamment. Un nettoyant ménager classique ne l’enlève pas : il est alcalin, et le voile est un dépôt calcaire.",
 [("Pourquoi il apparaît",
   ["Quand on réalise les joints d’un carrelage, l’eau du mortier dissout une partie du ciment et le remonte à la surface. En séchant, cette eau s’évapore et laisse derrière elle les minéraux qu’elle transportait : c’est le voile.",
    "Il est donc normal et systématique, pas le signe d’un travail bâclé. Ce qui varie, c’est son épaisseur : elle dépend de la quantité d’eau employée, de la porosité du carreau et du soin apporté à l’éponge de finition. Un carrelage poreux ou texturé retient beaucoup plus qu’un grès cérame lisse."]),
  ("Le calendrier, qui compte plus que le produit",
   ["Le voile ne se retire pas immédiatement. Les joints ont besoin de durcir, et un produit acide appliqué sur un joint frais le ronge : il devient friable, poudreux, et il faudra le refaire. Comptez une semaine minimum, deux si la pièce est peu ventilée.",
    "À l’inverse, attendre des mois n’aide pas. Le voile durcit et se lie au support, surtout sur un carrelage mat ou structuré. La fenêtre confortable se situe entre une et quatre semaines après le jointoiement."]),
  ("La méthode",
   ["Le sol est d’abord mouillé à l’eau claire. Cette étape est souvent sautée, et c’est une erreur : un carreau poreux sec absorbe le produit acide, qui devient beaucoup plus difficile à rincer et peut laisser une auréole.",
    "Le produit est ensuite appliqué dilué selon la notice, jamais pur. On le laisse agir quelques minutes sans le laisser sécher — un décapant qui sèche sur place recristallise et crée un deuxième problème par-dessus le premier. On frotte à la monobrosse ou à la brosse selon la surface.",
    "Le rinçage est la partie que tout le monde écourte, et c’est celle qui détermine le résultat. Il faut rincer à l’eau claire deux fois, en changeant l’eau entre les deux. Un rinçage insuffisant laisse un résidu acide qui continue de travailler sur les joints et qui ternit le carreau."]),
  ("Les supports qui ne le supportent pas",
   ["Le marbre, le travertin, la pierre calcaire et la terre cuite non traitée réagissent à l’acide : il les attaque et les mate irrémédiablement. Sur ces supports, on utilise un produit spécifique neutre, plus lent et plus cher, mais sans alternative.",
    "En cas de doute sur la nature du carreau, l’essai se fait dans un angle, sous un meuble, avant de traiter la pièce. C’est une minute qui évite de refaire un sol."])],
 [("Peut-on utiliser du vinaigre blanc ?",
   "Sur un voile léger et un grès cérame, ça peut suffire. Sur un voile épais, c’est trop faible, et sur une pierre naturelle c’est aussi agressif qu’un acide fort. Le vinaigre n’est pas une option douce, il est simplement moins concentré."),
  ("Que faire si le voile revient après nettoyage ?",
   "C’est presque toujours un rinçage insuffisant : le produit a redéposé ce qu’il avait dissous. Un deuxième rinçage abondant à l’eau claire suffit en général. Si le voile réapparaît plusieurs fois, il peut s’agir de remontées d’humidité, et c’est un autre problème."),
  ("Est-ce compris dans un nettoyage de fin de chantier ?",
   "Oui, quand le carrelage est concerné. C’est un des postes les plus techniques de la prestation, et celui qui demande le plus de précaution sur le choix du produit.")],
 ("/nettoyage-fin-de-chantier/", "Nettoyage de fin de chantier")),

("nettoyage-bureaux-journee-ou-hors-horaires",
 "Nettoyage de bureaux : en journée ou hors horaires",
 "Nettoyage de bureaux : <em>en journée ou hors horaires</em>",
 "Hors horaires pour les tâches bruyantes et les sols, en journée pour les sanitaires et les points de contact : le bon découpage dépend moins du confort que de la nature des tâches.",
 "Le nettoyage hors horaires — tôt le matin, en soirée ou le week-end — convient aux tâches bruyantes ou gênantes : aspiration, lavage des sols, vitrerie, salles de réunion. Le passage en journée a un intérêt propre sur les sanitaires, les points de contact et les espaces de restauration, où l’entretien doit suivre l’usage réel plutôt que l’attendre. La plupart des entreprises gagnent à combiner les deux.",
 [("Ce que le hors-horaires permet",
   ["Aspirer entre des jambes, laver un sol qu’on traverse toutes les trente secondes ou nettoyer une vitre derrière un poste occupé donne un résultat médiocre et dérange tout le monde. Ces tâches demandent l’espace libre.",
    "Il y a aussi un effet sur la durée : une même surface se nettoie beaucoup plus vite sans contournement. Sur un plateau de bureaux, l’écart entre un passage libre et un passage en activité peut dépasser trente pour cent de temps, ce qui se répercute sur le devis.",
    "Enfin, le résultat est visible au bon moment. Des locaux nettoyés le soir accueillent les équipes le matin dans un état impeccable, ce qui n’est jamais le cas d’un nettoyage étalé dans la journée."]),
  ("Ce que le passage en journée apporte",
   ["Les sanitaires sont le seul poste où la logique s’inverse. Un sanitaire nettoyé à 19 h est propre à 8 h, mais il ne l’est plus à 15 h. Sur les sites à effectif important, un réapprovisionnement et une reprise en milieu de journée changent davantage le ressenti que n’importe quelle amélioration du passage du soir.",
    "Même chose pour les espaces de restauration et les machines à café : ils se salissent à heure fixe, et les entretenir douze heures plus tard n’a pas de sens.",
    "Les points de contact — poignées, interrupteurs, boutons d’ascenseur, rampes — relèvent de la même logique si l’objectif est sanitaire et pas seulement visuel."]),
  ("Le découpage qui fonctionne",
   ["Le schéma le plus répandu associe un passage principal hors horaires, qui traite les sols, les bureaux, les salles de réunion et les parties communes, et un passage court en journée sur les sanitaires et la restauration. Le deuxième est bref et coûte peu.",
    "Sur les petites structures, un seul passage hors horaires suffit souvent, avec un réapprovisionnement des consommables suffisamment généreux pour tenir la journée.",
    "Le point à ne pas négliger : les accès. Un passage hors horaires suppose des clés, un code d’alarme ou un badge, et une confiance qui se construit. C’est aussi pour cette raison qu’une équipe stable vaut mieux qu’un roulement — ce sont les mêmes personnes qui détiennent les accès."]),
  ("La fréquence, selon l’effectif",
   ["Un passage quotidien se justifie à partir d’une vingtaine de personnes, ou en dessous si l’activité salit — cabinet médical, atelier, restauration. Entre dix et vingt personnes, trois passages par semaine suffisent généralement, à condition que les sanitaires soient repris à chaque fois.",
    "En dessous de dix personnes, deux passages hebdomadaires tiennent la route. Ce qui compte alors, c’est moins la fréquence que la constance : un passage sauté se voit immédiatement quand il n’y en a que deux."])],
 [("Faut-il confier ses clés à l’entreprise de nettoyage ?",
   "C’est l’usage pour un passage hors horaires, et c’est encadré : remise contre décharge, équipe nommément désignée, restitution à la fin du contrat. C’est un argument de plus pour préférer une équipe stable à un roulement de prestataires."),
  ("Le week-end coûte-t-il plus cher ?",
   "Le samedi se pratique couramment sans majoration particulière. Le dimanche et les jours fériés relèvent d’une majoration légale, et se réservent aux cas où il n’y a pas d’autre créneau."),
  ("Peut-on commencer par un essai ?",
   "Oui, et c’est même recommandé. Un mois permet de constater ce qui manque ou ce qui est superflu, et d’ajuster la fréquence avant de s’engager sur une durée.")],
 ("/nettoyage-bureaux/", "Nettoyage de bureaux")),
]

GUIDES += [

("nettoyage-veranda-toiture",
 "Nettoyage de véranda : pourquoi la toiture compte plus que les parois",
 "Nettoyage de véranda : <em>la toiture d’abord</em>",
 "Sur une véranda, c’est la toiture qui assombrit la pièce, pas les parois. Mousses, pollens et dépôts s’y accumulent à plat et bloquent la lumière bien avant que les vitres latérales ne se voient sales.",
 "Sur une véranda, la toiture reçoit dix fois plus de dépôts que les parois verticales, parce que rien ne la lave : la pluie ruisselle sur une vitre verticale, elle stagne sur une pente faible. Mousses, pollens, fientes et poussières s’y accumulent et font perdre jusqu’à un tiers de luminosité, alors même que les parois paraissent propres.",
 [("Pourquoi la toiture se salit dix fois plus vite",
   ["Une vitre verticale est auto-nettoyante par la pluie : l’eau descend et emporte une partie des dépôts. Une toiture de véranda a une pente de quelques degrés seulement. L’eau y stagne, s’évapore sur place, et laisse derrière elle tout ce qu’elle transportait.",
    "S’ajoute l’environnement immédiat. Un arbre au-dessus signifie du pollen au printemps, de la sève en été, des feuilles et du tanin à l’automne. Le tanin des feuilles mortes tache durablement le polycarbonate, et cette tache ne part plus passé quelques mois.",
    "Enfin, les profilés et les joints retiennent l’humidité. C’est là que la mousse s’installe en premier, souvent sur le bord bas, avant de gagner la surface."]),
  ("Ce que ça change concrètement dans la pièce",
   ["Une toiture encrassée ne se voit pas d’en bas : on regarde à travers, pas vers elle. Ce qu’on constate, c’est que la véranda est devenue moins agréable sans savoir pourquoi. La luminosité a baissé progressivement, sur deux ou trois ans, et l’œil s’est habitué.",
    "L’écart est spectaculaire après nettoyage, et c’est la remarque qui revient le plus souvent chez nos clients : ce n’est pas la propreté qu’ils remarquent, c’est la lumière."]),
  ("Les matériaux, et ce qu’ils supportent",
   ["Le verre feuilleté se nettoie comme n’importe quel vitrage, avec mouilleur et raclette. C’est le cas le plus simple.",
    "Le polycarbonate alvéolaire demande plus de précaution : il raye facilement, et un produit trop agressif le ternit définitivement. Pas de grattoir, pas d’abrasif, pas de nettoyeur haute pression — la pression fait pénétrer l’eau dans les alvéoles, qui deviennent troubles et ne sèchent plus.",
    "Les profilés aluminium laqués supportent mal les produits acides et les brosses dures. Ils se nettoient avec un produit neutre, ce qui prolonge la tenue du laquage."]),
  ("À quelle fréquence",
   ["Deux passages par an suffisent dans la plupart des cas : un au printemps après les pollens, un à l’automne après la chute des feuilles. Sous un arbre, trois passages sont plus réalistes.",
    "L’erreur courante est d’attendre que ce soit visible. À ce stade, la mousse est installée et le nettoyage devient un décapage, plus long et plus cher. Un entretien régulier revient nettement moins cher qu’un rattrapage tous les cinq ans."])],
 [("Peut-on utiliser un nettoyeur haute pression ?",
   "Sur du verre à la rigueur, jamais sur du polycarbonate ni sur les joints. La pression décolle les mastics et fait entrer l’eau dans les alvéoles, ce qui rend la plaque définitivement trouble."),
  ("Le nettoyage de la toiture est-il plus cher ?",
   "Il demande plus de temps et un accès par le dessus, donc oui, il pèse plus que les parois dans un devis. C’est aussi ce qui change le plus le résultat."),
  ("Et les gouttières de la véranda ?",
   "Elles se bouchent avec les mêmes feuilles. Les vider au moment du nettoyage évite les débordements et les infiltrations sur les profilés.")],
 ("/nettoyage-vitres/", "Nettoyage de vitres")),

("check-list-etat-des-lieux-sortie",
 "Remise en état avant état des lieux : la check-list",
 "État des lieux de sortie : <em>la check-list</em>",
 "Ce qu’un état des lieux de sortie vérifie réellement, poste par poste, et les points que les locataires oublient presque toujours : hottes, joints, radiateurs, volets roulants et trous de fixation.",
 "Un état des lieux de sortie se compare au document d’entrée, pas à un standard absolu. Les postes qui font perdre une caution sont presque toujours les mêmes : la hotte et le four, les joints de salle de bains, les trous de fixation non rebouchés, les vitres, et la poussière derrière les radiateurs et dans les volets roulants. Le reste se règle avec un nettoyage courant.",
 [("La cuisine, premier poste de litige",
   ["La hotte est le point numéro un. Le filtre métallique se dégraisse au lave-vaisselle ou dans de l’eau très chaude additionnée de cristaux de soude ; le corps de hotte se dégraisse à la main. Un filtre saturé est visible immédiatement et se chiffre au remplacement.",
    "Le four vient ensuite, y compris les glissières, la vitre intérieure et le joint de porte. Sur un four à pyrolyse, un cycle complet règle la question, à condition de retirer les grilles.",
    "Les plans de travail, le contour de l’évier et le joint silicone entre le plan et la crédence terminent le poste. Un joint noirci se remplace, il ne se nettoie plus."]),
  ("La salle de bains",
   ["Les joints de douche et de baignoire sont scrutés systématiquement. Un joint moisi en profondeur ne revient pas au blanc : il se change, et c’est une opération de quelques euros de matériel.",
    "Le calcaire sur les parois, la robinetterie et le pommeau se traite à l’acide doux. Les siphons se démontent et se vident : c’est invisible sur le constat, mais l’odeur ne l’est pas."]),
  ("Ce que tout le monde oublie",
   ["Les volets roulants : le coffre et les lames accumulent une poussière grasse que personne ne pense à faire. Les radiateurs : la poussière derrière et entre les ailettes. Les grilles de ventilation, souvent complètement obstruées après deux ou trois ans.",
    "Les trous de fixation doivent être rebouchés et poncés, pas seulement bouchés. Un enduit non poncé et non repeint se voit autant qu’un trou.",
    "Enfin, les vitres et leurs encadrements. C’est le poste le plus visible d’un logement vide, parce qu’il n’y a plus de meubles pour détourner le regard."]),
  ("Faire soi-même ou faire faire",
   ["Un studio ou un deux-pièces bien entretenu se remet en état en une journée à deux personnes. Au-delà, ou après plusieurs années d’occupation, le temps réel dépasse largement l’estimation.",
    "Le calcul est simple : le coût d’une remise en état professionnelle se compare à la part de caution qui serait retenue, et à la valeur du week-end qu’on y consacre. Sur un logement familial, la prestation coûte presque toujours moins cher que la retenue."])],
 [("Le logement doit-il être vide au moment du nettoyage ?",
   "Oui, entièrement. Un meuble restant empêche de traiter le sol et le mur derrière, et ce sont précisément les endroits que l’état des lieux regarde."),
  ("Faut-il repeindre ?",
   "Seulement si l’usure dépasse l’usage normal, ou si le bail le prévoit. Des traces de meubles après trois ans relèvent de la vétusté, pas de la dégradation."),
  ("Combien de temps avant l’état des lieux intervenir ?",
   "La veille ou l’avant-veille. Plus tôt, la poussière se redépose dans un logement vide et fermé ; le jour même, il n’y a plus de marge si quelque chose doit être repris.")],
 ("/nettoyage-fin-de-chantier/", "Nettoyage de fin de chantier")),

("choisir-entreprise-nettoyage-le-mans",
 "Entreprise de nettoyage au Mans : comment choisir",
 "Choisir une entreprise de nettoyage <em>au Mans</em>",
 "Adresse vérifiable, SIRET public, assurance RC Pro, devis détaillé poste par poste et interlocuteur unique : les cinq points à contrôler avant de signer, et comment reconnaître une plateforme d’un vrai prestataire.",
 "Cinq vérifications suffisent : l’entreprise a-t-elle une adresse réelle et un SIRET consultable, est-elle assurée en responsabilité civile professionnelle, le devis détaille-t-il les postes plutôt qu’un forfait global, la personne qui chiffre est-elle celle qui intervient, et l’équipe reste-t-elle la même d’un passage à l’autre. Un prestataire qui coche ces cinq points est rarement le moins cher, et presque toujours le moins risqué.",
 [("Reconnaître une plateforme d’un prestataire",
   ["Beaucoup de sites qui remontent sur « nettoyage Le Mans » ne sont pas des entreprises du Mans. Ce sont des plateformes nationales qui publient la même page pour des centaines de villes, collectent votre demande et la revendent à un prestataire local. Rien d’illégal, mais cela ajoute un intermédiaire et personne à rappeler si ça se passe mal.",
    "Les signes sont faciles à repérer : aucune adresse de rue sur le site, un numéro en 09 ou un formulaire seul, des pages de ville interchangeables où seul le nom change, et jamais de photo de chantier réel. Une entreprise qui travaille vraiment ici affiche où elle est."]),
  ("Le SIRET et l’assurance",
   ["Le SIRET ou le SIREN doit figurer sur le devis et dans les mentions légales. Il se vérifie en trente secondes sur l’annuaire des entreprises. Une société sans numéro consultable, ou dont le numéro ne correspond pas au nom annoncé, est un signal d’arrêt.",
    "L’attestation de responsabilité civile professionnelle se demande, tout simplement. Un nettoyeur intervient chez vous avec de l’eau, des produits et parfois du matériel d’élévation : une vitre cassée ou un sol abîmé doit être couvert. Une entreprise sérieuse fournit l’attestation sans qu’on insiste."]),
  ("Lire un devis de nettoyage",
   ["Un devis utile détaille les postes : surfaces concernées, fréquence, ce qui est inclus et ce qui ne l’est pas. Un forfait global sans détail rend toute discussion impossible le jour où le résultat ne correspond pas.",
    "Méfiez-vous des prix au mètre carré annoncés avant visite. Sur du vitrage, l’accès et l’état initial font varier le temps de travail du simple au double : un chiffre donné sans avoir vu les lieux sera révisé, ou le travail sera bâclé pour tenir le prix.",
    "Vérifiez aussi ce qui se passe si le résultat ne convient pas. Un prestataire local peut repasser le lendemain ; une plateforme vous renverra vers un service client."]),
  ("La stabilité de l’équipe",
   ["Pour un contrat régulier, c’est le critère qui compte le plus sur la durée. Une équipe qui revient connaît vos accès, vos horaires, les pièces sensibles et vos exigences. Un roulement permanent oblige à tout réexpliquer, et la qualité suit la rotation.",
    "C’est aussi une question de confiance : un passage hors horaires suppose des clés ou un code d’alarme. On ne confie pas ça à une personne différente chaque semaine."])],
 [("Le moins cher est-il forcément mauvais ?",
   "Non, mais un écart important sur un même périmètre signifie presque toujours que le périmètre n’est pas le même. Comparez les postes du devis avant de comparer les totaux."),
  ("Faut-il signer un engagement de durée ?",
   "Pas nécessairement. Pour un contrat d’entretien, un mois d’essai permet d’ajuster la fréquence avant de s’engager, et un contrat sans durée minimale est parfaitement viable."),
  ("Comment vérifier les avis ?",
   "Les avis Google rattachés à une fiche d’établissement avec adresse valent plus que des témoignages sur un site. Regardez leur régularité dans le temps plutôt que leur nombre.")],
 ("/nettoyage-le-mans/", "Nettoyage au Mans")),

("prix-nettoyage-de-vitres-ce-qui-varie",
 "Combien coûte un nettoyage de vitres : ce qui fait varier le prix",
 "Prix d’un nettoyage de vitres : <em>ce qui le fait varier</em>",
 "Surface vitrée réelle, accès, état initial et fréquence : les quatre critères qui déterminent un devis de vitrerie, et pourquoi un prix au mètre carré annoncé sans visite ne tient jamais.",
 "Quatre critères déterminent le prix d’un nettoyage de vitres : la surface vitrée réelle — comptée en faces, pas en fenêtres —, l’accès — plain-pied, perche, échafaudage ou nacelle —, l’état initial du vitrage, et la fréquence de passage. Un prix au mètre carré annoncé avant visite ne tient pas, parce que l’accès seul peut doubler le temps de travail à surface égale.",
 [("La surface se compte en faces",
   ["Une fenêtre a deux faces. Une baie coulissante à deux vantaux en a quatre. Une véranda ajoute sa toiture, qui compte souvent plus que l’ensemble des parois. C’est la première source de malentendu sur un devis : le client compte des ouvertures, le professionnel compte des surfaces à traiter.",
    "S’ajoutent les éléments qui vont avec : encadrements, montants, appuis, rails de coulissants. Ils sont inclus dans un travail sérieux, et ils prennent du temps."]),
  ("L’accès, le critère qui pèse le plus",
   ["Une vitre de plain-pied se traite en quelques minutes. La même à quatre mètres, accessible à la perche télescopique, prend deux à trois fois plus longtemps. La même derrière un massif, un auvent ou une descente de gouttière peut nécessiter un échafaudage — et le montage coûte plus cher que le nettoyage.",
    "C’est précisément pour cette raison qu’un chiffrage sérieux passe par une visite quand la configuration n’est pas évidente. La perche couvre la grande majorité des maisons et beaucoup de rez-de-chaussée commerciaux, ce qui maintient le coût bas ; les exceptions se voient sur place, pas sur une photo."]),
  ("L’état initial",
   ["Un vitrage entretenu se lave. Un vitrage laissé plusieurs années se décape : calcaire incrusté, résidus de pollution, traces de chantier anciennes. Le premier passage sur un vitrage négligé coûte donc plus cher que les suivants, et c’est normal.",
    "Certains états relèvent d’ailleurs d’une remise en état plutôt que d’un nettoyage : projections de peinture, silicone, laitance de ciment, rayures d’adhésif. Ce sont des postes à part, et ils doivent apparaître comme tels sur le devis."]),
  ("La fréquence",
   ["Le tarif par passage baisse avec la régularité, pour une raison mécanique : un vitrage entretenu se nettoie plus vite, et un passage récurrent se cale sur une tournée existante sans déplacement dédié.",
    "Le bon calcul n’est donc pas le prix d’un passage mais le coût annuel. Pour un commerce, un contrat hebdomadaire ou bimensuel revient souvent moins cher sur l’année que quatre grosses interventions, avec une vitrine présentable en permanence au lieu de quatre fois par an."]),
  ("Pourquoi nous n’affichons pas de tarif",
   ["Un prix affiché sans avoir vu les lieux est un prix qu’il faudra corriger, ou un travail qu’il faudra bâcler pour le tenir. Nous préférons nous déplacer, regarder l’accès et l’état réel, et envoyer un devis détaillé poste par poste sous 24 heures. Il est gratuit, et il ne bouge pas entre la signature et la facture."])],
 [("Le devis est-il payant ?",
   "Non, et la visite préalable non plus. Elle est sans engagement."),
  ("Le premier passage coûte-t-il plus cher ?",
   "Sur un vitrage négligé depuis longtemps, oui : c’est un décapage, pas un lavage. Les passages suivants reviennent au tarif d’entretien."),
  ("Y a-t-il un montant minimum ?",
   "Sur Le Mans et la première couronne, non : la proximité permet d’accepter une intervention courte. Sur les communes les plus éloignées, nous groupons plutôt que d’imposer un minimum.")],
 ("/nettoyage-vitres/", "Nettoyage de vitres")),

("nettoyage-apres-demenagement",
 "Nettoyage après déménagement : avant de rendre les clés",
 "Nettoyage après déménagement, <em>avant de rendre les clés</em>",
 "Un logement vide ne pardonne rien : sans meubles, chaque trace se voit. Ce qu’il faut traiter en priorité, dans quel ordre, et pourquoi le faire une fois le camion parti change tout.",
 "Un nettoyage après déménagement se fait impérativement une fois le logement entièrement vide, jamais avant. L’ordre efficace est descendant : plafonds et luminaires, puis murs et menuiseries, puis vitres, puis cuisine et sanitaires, et enfin les sols. Compter une journée à deux personnes pour un deux-pièces bien entretenu, nettement plus après plusieurs années d’occupation.",
 [("Pourquoi un logement vide ne pardonne rien",
   ["Tant qu’il y a des meubles, l’œil est occupé. Une fois la pièce vide, il ne reste que les surfaces : et chaque trace de meuble, chaque auréole, chaque trou de fixation devient le seul élément à regarder.",
    "C’est aussi vrai pour les vitres. Dans un logement meublé, personne ne les remarque ; dans un logement vide, ce sont elles qui donnent le ton de la visite. C’est le poste le plus rentable d’une remise en état."]),
  ("L’ordre, et pourquoi il compte",
   ["On travaille de haut en bas, toujours. Nettoyer les sols avant les murs oblige à les refaire : tout ce qu’on décroche en hauteur retombe.",
    "Concrètement : plafonds, luminaires et détecteurs d’abord. Puis murs, plinthes, portes, poignées et interrupteurs. Puis les vitres et leurs encadrements. Puis la cuisine et la salle de bains, qui demandent le plus de temps. Les sols en dernier, et seulement à ce moment-là.",
    "Entre les deux, une étape sautée neuf fois sur dix : les placards, à l’intérieur. Ils sont systématiquement ouverts lors d’un état des lieux."]),
  ("Les points qui coûtent une caution",
   ["La hotte et le four en cuisine, les joints de douche en salle de bains, les trous de fixation non rebouchés et poncés, les volets roulants et leurs coffres, l’arrière des radiateurs, et les grilles de ventilation. Ce sont les six postes qui reviennent dans presque tous les constats.",
    "Un joint silicone moisi en profondeur ne se rattrape pas au nettoyage : il se change. C’est quelques euros de matériel et vingt minutes, contre une ligne sur le constat de sortie."]),
  ("Le faire soi-même, ou pas",
   ["Le jour du déménagement est le pire moment pour s’y mettre : tout le monde est fatigué, le camion attend, et le travail est bâclé. Si vous le faites vous-même, prévoyez une journée séparée, après le départ des meubles.",
    "Faire appel à un professionnel se justifie surtout au-delà du deux-pièces, ou quand le logement a été occupé plusieurs années. Le coût se compare à la retenue de caution évitée — et au week-end récupéré."])],
 [("Faut-il nettoyer si le logement va être rénové ?",
   "Oui pour l’état des lieux : il porte sur l’état à la restitution, pas sur ce que le propriétaire compte en faire ensuite."),
  ("Le nettoyage est-il obligatoire dans le bail ?",
   "Le bail impose de restituer le logement en bon état d’entretien. En pratique, cela revient au même : un logement rendu sale génère une retenue."),
  ("Combien de temps avant la restitution ?",
   "La veille ou l’avant-veille, une fois le logement totalement vide. Assez tôt pour corriger, assez tard pour que la poussière ne se redépose pas.")],
 ("/nettoyage-fin-de-chantier/", "Nettoyage de fin de chantier")),
]

GUIDES += [

("traces-de-peinture-sur-vitre",
 "Traces de peinture sur une vitre : les retirer sans rayer",
 "Traces de peinture sur une vitre, <em>sans rayer le verre</em>",
 "Une goutte de peinture se retire à la lame, à plat et sur verre mouillé. La technique est simple, les erreurs coûtent cher : une lame à sec ou inclinée laisse une rayure définitive.",
 "Une trace de peinture sur une vitre se retire avec une lame de rasoir neuve, tenue quasiment à plat sur un verre abondamment mouillé, en poussant dans un seul sens. Le verre doit rester humide en permanence. Une lame utilisée à sec, inclinée, ou passée en va-et-vient laisse des micro-rayures irréversibles, et c’est de loin la cause de casse la plus fréquente en fin de chantier.",
 [("Pourquoi la lame, et pas un solvant",
   ["La peinture acrylique séchée sur du verre n’adhère pas chimiquement : elle forme un film posé dessus. C’est pourquoi elle se décolle mécaniquement très facilement, alors qu’un solvant mettrait longtemps et attaquerait les joints alentour.",
    "Le verre est par ailleurs beaucoup plus dur que l’acier d’une lame de rasoir. Une lame ne raye donc pas le verre par elle-même — ce qui raye, c’est une particule dure coincée entre les deux. D’où la règle absolue : beaucoup d’eau, pour que ces particules flottent au lieu d’être traînées."]),
  ("Le geste",
   ["On mouille abondamment la zone, au mouilleur ou à l’éponge. On tient la lame à environ dix degrés du verre, presque à plat. On pousse dans un seul sens, sans revenir en arrière. On re-mouille dès que la surface commence à sécher.",
    "La lame se change dès qu’elle accroche. Une lame émoussée demande d’appuyer, et c’est en appuyant qu’on raye. Une lame coûte quelques centimes, un vitrage rayé se remplace."]),
  ("Les verres à ne jamais gratter",
   ["Les vitrages à couche — autonettoyants, à contrôle solaire, à faible émissivité — ont une couche déposée en surface, parfois sur la face extérieure. La lame la retire, et le dommage est invisible sur le moment mais définitif : il apparaît en reflet, par plaques.",
    "Le plexiglas et le polycarbonate se rayent immédiatement, quelle que soit la précaution. Sur ces matériaux, on travaille au solvant doux et à la microfibre, avec de la patience.",
    "En cas de doute sur la nature du vitrage, l’essai se fait dans un angle bas, sur quelques millimètres. Trente secondes qui évitent de remplacer une baie."]),
  ("Les autres résidus de chantier",
   ["Le silicone frais s’enlève à la lame ; sec, il demande un solvant spécifique puis un passage de lame. Les adhésifs et étiquettes se décollent à chaud, au décapeur réglé bas, puis se nettoient au solvant.",
    "La laitance de ciment et le plâtre demandent un traitement acide dilué, pas une lame : gratter du ciment revient à frotter le verre avec de la pierre.",
    "C’est la raison pour laquelle le vitrage est le poste le plus technique d’un nettoyage de fin de chantier : chaque résidu appelle une méthode différente, et se tromper coûte une vitre."])],
 [("Peut-on utiliser un grattoir de plaque à induction ?",
   "C’est exactement le même outil, à condition que la lame soit neuve et le verre mouillé. Les précautions sont identiques."),
  ("Et l’acétone ou le white-spirit ?",
   "Ils fonctionnent sur certaines peintures mais attaquent les joints, les mastics et les menuiseries PVC. Sur un vitrage neuf en fin de chantier, c’est un risque inutile."),
  ("Une rayure peut-elle se rattraper ?",
   "Une micro-rayure superficielle s’atténue au polissage à l’oxyde de cérium, long et imparfait. Une rayure profonde, non : la vitre se remplace.")],
 ("/nettoyage-fin-de-chantier/", "Nettoyage de fin de chantier")),

("entretien-sols-bureaux-par-materiau",
 "Entretien des sols de bureaux selon leur matériau",
 "Entretien des sols de bureaux, <em>matériau par matériau</em>",
 "Moquette, parquet, carrelage, sol souple : chaque revêtement demande une méthode et une fréquence différentes, et le traiter comme le voisin l’abîme plus vite qu’il ne le nettoie.",
 "Un sol de bureau s’entretient selon son revêtement : la moquette s’aspire quotidiennement et s’injecte-extrait une à deux fois par an, le parquet se balaie à sec et se lave très peu humide, le carrelage supporte le lavage mécanisé, et le sol souple (PVC, linoléum) demande un produit neutre et un métallisant périodique. Le tort le plus fréquent est l’excès d’eau, qui dégrade parquet, souple et joints.",
 [("La moquette",
   ["L’aspiration quotidienne fait quatre-vingts pour cent du travail. Ce qui use une moquette, ce ne sont pas les taches mais le sable et les particules abrasives piétinées dans les fibres : elles coupent la fibre à la base et ternissent définitivement.",
    "Les taches se traitent immédiatement, en tamponnant du bord vers le centre — frotter étale et fait pénétrer. Un détachant s’essaie toujours sous un meuble avant d’être utilisé en évidence.",
    "Une à deux fois par an, une injection-extraction récupère ce que l’aspiration ne prend plus. C’est une opération humide qui demande de la ventilation et un temps de séchage : elle se planifie un vendredi soir ou un week-end."]),
  ("Le parquet et les sols stratifiés",
   ["L’ennemi est l’eau. Un parquet se balaie ou s’aspire à sec, et se lave avec une frange très essorée, presque sèche. L’eau stagnante gonfle les lames, ouvre les joints et décolle les stratifiés par les bords.",
    "Le produit doit être neutre ou spécifique bois. Un dégraissant alcalin mange la finition vitrifiée et laisse un aspect terne qu’aucun lavage ne rattrape.",
    "Sur un parquet vitrifié en bon état, un entretien régulier suffit des années. Une fois la vitrification percée, il faut rénover : ce n’est plus du nettoyage."]),
  ("Le carrelage et les sols durs",
   ["C’est le revêtement le plus tolérant. Il supporte l’autolaveuse, la monobrosse et les produits alcalins, ce qui permet un entretien rapide sur de grandes surfaces.",
    "Le point faible est le joint. Poreux, il retient la saleté et se décolore, surtout en clair. Un joint se traite ponctuellement avec une brosse et un produit adapté ; sur un local neuf, un hydrofuge de joints en amont évite des années de reprise.",
    "Sur un carrelage mat ou structuré, attention au produit trop chargé : il laisse un film qui retient la saleté et rend le sol progressivement plus gris à chaque lavage."]),
  ("Les sols souples : PVC et linoléum",
   ["Ce sont les plus répandus dans les bureaux, et les plus souvent maltraités. Ils demandent un produit neutre : un alcalin fort attaque l’émulsion de protection et met le revêtement à nu.",
    "Le linoléum en particulier ne supporte pas les produits basiques, qui le jaunissent. Le PVC accepte un peu plus, mais dans les deux cas la protection s’use et doit être renouvelée : décapage puis application d’un métallisant, en général une fois par an.",
    "Un sol souple qui noircit malgré des lavages fréquents n’a généralement plus de protection : on lave la matière elle-même, qui se salit de plus en plus vite. C’est le signe qu’il faut décaper et reprotéger, pas laver davantage."])],
 [("À quelle fréquence laver un sol de bureau ?",
   "Aspiration ou balayage quotidien dans les circulations, lavage deux à trois fois par semaine selon le passage. Les entrées et les sas justifient un rythme plus soutenu, surtout l’hiver."),
  ("Les tapis d’entrée servent-ils vraiment ?",
   "Beaucoup. Un tapis de longueur suffisante — au moins trois pas — retient l’essentiel du sable et de l’humidité, et réduit l’usure des sols de tout le bâtiment."),
  ("Qui fournit les produits et le matériel ?",
   "Le prestataire, dans un contrat d’entretien classique. Les consommables sanitaires font en revanche l’objet d’une ligne distincte, à préciser sur le devis.")],
 ("/nettoyage-bureaux/", "Nettoyage de bureaux")),

("vitrine-bailleur-ou-locataire",
 "Nettoyage de vitrine : bailleur ou locataire, qui s’en occupe",
 "Vitrine d’un local commercial : <em>qui la nettoie</em>",
 "L’entretien courant d’une vitrine incombe au locataire, les gros travaux au bailleur. La frontière se lit dans le bail, et en copropriété la façade ajoute un troisième acteur.",
 "Dans un bail commercial, l’entretien courant — dont le nettoyage de la vitrine — incombe au locataire, tandis que les réparations structurelles et le clos et couvert restent à la charge du bailleur. La répartition exacte figure dans le bail et dans l’inventaire des charges obligatoire depuis la loi Pinel. En copropriété, le nettoyage de la façade au-delà du linéaire commercial relève généralement du syndic.",
 [("La règle de base",
   ["Le principe est simple : ce qui relève de l’usage quotidien est au locataire, ce qui relève de la structure est au bailleur. Une vitrine sale est de l’usage ; une vitrine fissurée ou un châssis hors service relève du propriétaire.",
    "Depuis la loi Pinel de 2014, tout bail commercial doit comporter un inventaire précis des catégories de charges, impôts et travaux, avec leur répartition. C’est ce document qu’il faut lire avant de se poser la question : il tranche dans la plupart des cas."]),
  ("Les zones grises",
   ["Le nettoyage de la façade au-dessus de la vitrine, l’enseigne, le bandeau et l’auvent posent régulièrement question. En pratique, la réponse dépend de qui a posé l’élément : une enseigne installée par le locataire s’entretient par lui.",
    "En copropriété, la façade est une partie commune. Le nettoyage du linéaire commercial reste au locataire, mais tout ce qui dépasse relève de la copropriété — et donc du syndic, avec un vote en assemblée générale.",
    "Dernier cas fréquent : la vitrine donnant sur un passage couvert ou une galerie. Le règlement de la galerie impose souvent un standard d’entretien, parfois même un prestataire imposé."]),
  ("Ce qu’il faut vérifier avant de signer",
   ["L’inventaire des charges, article par article. La clause d’entretien et de réparations, en particulier ce qu’elle met à la charge du preneur. L’existence d’un règlement de copropriété ou de galerie qui imposerait un standard.",
    "Pour un local repris en cours de bail, l’état des lieux d’entrée est déterminant : une vitrine déjà dégradée et non consignée deviendra votre problème à la sortie."]),
  ("En pratique",
   ["Dans l’immense majorité des cas, le commerçant fait nettoyer sa vitrine, et cela relève de ses charges d’exploitation. C’est aussi son intérêt direct : la vitrine est le premier argument commercial du local.",
    "Pour un ensemble de plusieurs commerces, un contrat groupé passé par le bailleur ou l’association de commerçants revient souvent moins cher que des contrats individuels, avec un rendu homogène sur toute la rue."])],
 [("Le nettoyage de vitrine est-il déductible ?",
   "Pour un commerçant, c’est une charge d’exploitation déductible du résultat, comme tout service lié à l’exploitation du local. Votre comptable confirmera selon votre régime."),
  ("Le bailleur peut-il imposer un prestataire ?",
   "Dans un centre commercial ou une galerie, oui, si le règlement le prévoit. Dans un bail classique en pied d’immeuble, c’est rare et cela doit être écrit."),
  ("Qui paie si la vitrine est cassée pendant le nettoyage ?",
   "L’assurance responsabilité civile professionnelle du prestataire. C’est la raison pour laquelle il faut en demander l’attestation avant de confier le travail.")],
 ("/nettoyage-vitres/", "Nettoyage de vitres")),

("nettoyage-copropriete-parties-communes",
 "Entretien des parties communes : ce qu’un syndic doit prévoir",
 "Parties communes : <em>ce qu’un syndic doit prévoir</em>",
 "Halls, cages d’escalier, ascenseurs, locaux poubelles et vitrages : le périmètre d’un contrat d’entretien de copropriété, les fréquences usuelles, et les postes qu’on oublie au moment du devis.",
 "Un contrat d’entretien de parties communes couvre généralement les halls et circulations, les cages d’escalier, les ascenseurs, les locaux poubelles et les vitrages communs. Les fréquences usuelles vont du passage quotidien en immeuble de standing à un passage hebdomadaire en petite copropriété. Les postes le plus souvent oubliés au devis sont la sortie et la rentrée des conteneurs, les parkings et les vitrages en hauteur.",
 [("Le périmètre courant",
   ["Le hall et les circulations constituent le cœur du contrat : c’est ce que voient les résidents et les visiteurs tous les jours, et c’est ce sur quoi se juge la qualité de la prestation.",
    "Les cages d’escalier demandent un traitement différencié : les marches se lavent, les rampes et les mains courantes sont des points de contact, et les paliers accumulent la poussière dans les angles.",
    "Les ascenseurs concentrent les traces de doigts et les sols marqués. Les locaux poubelles demandent un lavage et une désinfection, et souvent un traitement anti-odeurs en été."]),
  ("Les postes qu’on oublie",
   ["La sortie et la rentrée des conteneurs est la première source de litige : elle n’est pas du nettoyage, elle est chronophage, et elle doit figurer explicitement au contrat avec ses jours.",
    "Les vitrages communs — portes d’entrée, impostes, fenêtres de cage d’escalier — sont fréquemment absents du périmètre, puis réclamés ensuite. Les vitrages en hauteur relèvent d’ailleurs souvent d’une prestation distincte, une à deux fois par an.",
    "Les parkings, les caves et les locaux vélos complètent la liste. Un balayage mensuel suffit généralement, mais s’il n’est pas au contrat il ne sera pas fait."]),
  ("Les fréquences usuelles",
   ["En immeuble de standing ou à forte fréquentation, un passage quotidien sur le hall et les circulations, avec les escaliers deux à trois fois par semaine.",
    "En copropriété de taille moyenne, trois passages hebdomadaires couvrent correctement le besoin, avec les vitrages une fois par mois.",
    "En petite copropriété, un passage hebdomadaire est la norme. Ce qui compte alors, c’est la régularité : un passage sauté sur quatre par mois se voit immédiatement."]),
  ("Ce qu’un conseil syndical devrait exiger",
   ["Un cahier des charges qui liste les zones, les tâches et les fréquences, plutôt qu’un forfait global. Sans ce document, aucun désaccord ne peut être arbitré.",
    "Un cahier de passage, papier ou numérique, signé à chaque intervention. C’est la seule preuve objective en cas de contestation en assemblée générale.",
    "Une équipe stable et nommément identifiée. Sur un contrat de parties communes, le roulement permanent est la première cause de baisse de qualité, parce que personne ne s’approprie le site."])],
 [("Le contrat doit-il être voté en assemblée générale ?",
   "Le choix du prestataire relève généralement du syndic dans le cadre du budget voté. Un changement significatif de périmètre ou de montant passe en assemblée."),
  ("Le prestataire fournit-il les consommables ?",
   "Les produits et le matériel, oui. Les sacs poubelle, ampoules et consommables divers font l’objet d’une ligne distincte : à vérifier avant de comparer deux devis."),
  ("Peut-on tester avant de s’engager ?",
   "Oui, un mois d’essai est courant et permet d’ajuster le cahier des charges avant de fixer la durée.")],
 ("/nettoyage-bureaux/", "Nettoyage de bureaux")),
]
